#!/usr/bin/env python
#
# This script dynamically generates the YAML filter configuration for the
# dorny/paths-filter GitHub Action. It scans the 'services/' directory
# and creates a filter for each subdirectory that contains a Dockerfile.
#

import os

SERVICES_DIR = "services"

def generate_filters():
    """
    Scans the services directory and prints a YAML block of filters
    for each service found.
    """
    if not os.path.isdir(SERVICES_DIR):
        print(f"Error: Directory '{SERVICES_DIR}' not found.", file=sys.stderr)
        return

    print("# Auto-generated by scripts/generate-ci-filters.py")
    for service_name in sorted(os.listdir(SERVICES_DIR)):
        service_path = os.path.join(SERVICES_DIR, service_name)
        dockerfile_path = os.path.join(service_path, "Dockerfile")

        if os.path.isdir(service_path) and os.path.exists(dockerfile_path):
            print(f"{service_name}:")
            print(f"  - '{service_path}/**'")

if __name__ == "__main__":
    import sys
    generate_filters()
