"""Models for the minimal controlled offline runner review."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any


class ControlledOfflineRunnerMinimalReviewState(StrEnum):
    NOT_READY = "NOT_READY"
    CONTROLLED_OFFLINE_RUNNER_MINIMAL_REVIEW_INPUT_INVALID = "CONTROLLED_OFFLINE_RUNNER_MINIMAL_REVIEW_INPUT_INVALID"
    CONTROLLED_OFFLINE_RUNNER_MINIMAL_REVIEW_BLOCKED = "CONTROLLED_OFFLINE_RUNNER_MINIMAL_REVIEW_BLOCKED"
    CONTROLLED_OFFLINE_RUNNER_MINIMAL_REVIEW_COMPLETED_WITH_WARNINGS = "CONTROLLED_OFFLINE_RUNNER_MINIMAL_REVIEW_COMPLETED_WITH_WARNINGS"
    CONTROLLED_OFFLINE_RUNNER_MINIMAL_REVIEW_COMPLETED = "CONTROLLED_OFFLINE_RUNNER_MINIMAL_REVIEW_COMPLETED"
    READY_FOR_SYNTHETIC_MARKET_SCENARIO_V1 = "READY_FOR_SYNTHETIC_MARKET_SCENARIO_V1"


class ControlledOfflineRunnerMinimalReviewDecision(StrEnum):
    BLOCK_CONTROLLED_OFFLINE_RUNNER_MINIMAL_REVIEW = "BLOCK_CONTROLLED_OFFLINE_RUNNER_MINIMAL_REVIEW"
    REQUIRE_CONTROLLED_OFFLINE_RUNNER_MINIMAL_FIXES = "REQUIRE_CONTROLLED_OFFLINE_RUNNER_MINIMAL_FIXES"
    REQUIRE_CONTROLLED_OFFLINE_RUNNER_DETERMINISM_FIXES = "REQUIRE_CONTROLLED_OFFLINE_RUNNER_DETERMINISM_FIXES"
    REQUIRE_CONTROLLED_OFFLINE_RUNNER_MARKET_SCENARIO_FIXES = "REQUIRE_CONTROLLED_OFFLINE_RUNNER_MARKET_SCENARIO_FIXES"
    REQUIRE_CONTROLLED_OFFLINE_RUNNER_ACCOUNT_SNAPSHOT_FIXES = "REQUIRE_CONTROLLED_OFFLINE_RUNNER_ACCOUNT_SNAPSHOT_FIXES"
    REQUIRE_CONTROLLED_OFFLINE_RUNNER_BROKER_SNAPSHOT_FIXES = "REQUIRE_CONTROLLED_OFFLINE_RUNNER_BROKER_SNAPSHOT_FIXES"
    REQUIRE_CONTROLLED_OFFLINE_RUNNER_STRATEGY_SIGNAL_FIXES = "REQUIRE_CONTROLLED_OFFLINE_RUNNER_STRATEGY_SIGNAL_FIXES"
    REQUIRE_CONTROLLED_OFFLINE_RUNNER_RISK_GUARD_FIXES = "REQUIRE_CONTROLLED_OFFLINE_RUNNER_RISK_GUARD_FIXES"
    REQUIRE_CONTROLLED_OFFLINE_RUNNER_READ_ONLY_DECISION_FIXES = "REQUIRE_CONTROLLED_OFFLINE_RUNNER_READ_ONLY_DECISION_FIXES"
    REQUIRE_CONTROLLED_OFFLINE_RUNNER_JOURNAL_FIXES = "REQUIRE_CONTROLLED_OFFLINE_RUNNER_JOURNAL_FIXES"
    REQUIRE_CONTROLLED_OFFLINE_RUNNER_METRICS_FIXES = "REQUIRE_CONTROLLED_OFFLINE_RUNNER_METRICS_FIXES"
    REQUIRE_CONTROLLED_OFFLINE_RUNNER_REPORT_FIXES = "REQUIRE_CONTROLLED_OFFLINE_RUNNER_REPORT_FIXES"
    APPROVE_CONTROLLED_OFFLINE_RUNNER_MINIMAL_REVIEW = "APPROVE_CONTROLLED_OFFLINE_RUNNER_MINIMAL_REVIEW"


class ControlledOfflineRunnerMinimalReviewRisk(StrEnum):
    CONTROLLED_OFFLINE_RUNNER_MINIMAL_NOT_APPROVED = "CONTROLLED_OFFLINE_RUNNER_MINIMAL_NOT_APPROVED"
    CONTROLLED_OFFLINE_RUNNER_NOT_DETERMINISTIC = "CONTROLLED_OFFLINE_RUNNER_NOT_DETERMINISTIC"
    CONTROLLED_OFFLINE_RUNNER_MARKET_SCENARIO_REVIEW_FAILED = "CONTROLLED_OFFLINE_RUNNER_MARKET_SCENARIO_REVIEW_FAILED"
    CONTROLLED_OFFLINE_RUNNER_ACCOUNT_SNAPSHOT_REVIEW_FAILED = "CONTROLLED_OFFLINE_RUNNER_ACCOUNT_SNAPSHOT_REVIEW_FAILED"
    CONTROLLED_OFFLINE_RUNNER_BROKER_SNAPSHOT_REVIEW_FAILED = "CONTROLLED_OFFLINE_RUNNER_BROKER_SNAPSHOT_REVIEW_FAILED"
    CONTROLLED_OFFLINE_RUNNER_STRATEGY_SIGNAL_REVIEW_FAILED = "CONTROLLED_OFFLINE_RUNNER_STRATEGY_SIGNAL_REVIEW_FAILED"
    CONTROLLED_OFFLINE_RUNNER_RISK_GUARD_REVIEW_FAILED = "CONTROLLED_OFFLINE_RUNNER_RISK_GUARD_REVIEW_FAILED"
    CONTROLLED_OFFLINE_RUNNER_READ_ONLY_DECISION_REVIEW_FAILED = "CONTROLLED_OFFLINE_RUNNER_READ_ONLY_DECISION_REVIEW_FAILED"
    CONTROLLED_OFFLINE_RUNNER_JOURNAL_REVIEW_FAILED = "CONTROLLED_OFFLINE_RUNNER_JOURNAL_REVIEW_FAILED"
    CONTROLLED_OFFLINE_RUNNER_METRICS_REVIEW_FAILED = "CONTROLLED_OFFLINE_RUNNER_METRICS_REVIEW_FAILED"
    CONTROLLED_OFFLINE_RUNNER_REPORT_REVIEW_FAILED = "CONTROLLED_OFFLINE_RUNNER_REPORT_REVIEW_FAILED"
    REAL_BROKER_BOUNDARY_VIOLATION = "REAL_BROKER_BOUNDARY_VIOLATION"
    REAL_SECRET_BOUNDARY_VIOLATION = "REAL_SECRET_BOUNDARY_VIOLATION"
    NETWORK_BOUNDARY_VIOLATION = "NETWORK_BOUNDARY_VIOLATION"
    ORDER_EXECUTION_BOUNDARY_VIOLATION = "ORDER_EXECUTION_BOUNDARY_VIOLATION"
    ACCOUNT_ACCESS_BOUNDARY_VIOLATION = "ACCOUNT_ACCESS_BOUNDARY_VIOLATION"
    DATA_ACCESS_BOUNDARY_VIOLATION = "DATA_ACCESS_BOUNDARY_VIOLATION"
    PREMATURE_SYNTHETIC_MARKET_SCENARIO_V1 = "PREMATURE_SYNTHETIC_MARKET_SCENARIO_V1"


class ControlledOfflineRunnerMinimalReviewRecommendation(StrEnum):
    APPROVE_CONTROLLED_OFFLINE_RUNNER_MINIMAL_FIRST = "APPROVE_CONTROLLED_OFFLINE_RUNNER_MINIMAL_FIRST"
    FIX_CONTROLLED_OFFLINE_RUNNER_DETERMINISM = "FIX_CONTROLLED_OFFLINE_RUNNER_DETERMINISM"
    FIX_CONTROLLED_OFFLINE_MARKET_SCENARIO = "FIX_CONTROLLED_OFFLINE_MARKET_SCENARIO"
    FIX_CONTROLLED_OFFLINE_ACCOUNT_SNAPSHOT = "FIX_CONTROLLED_OFFLINE_ACCOUNT_SNAPSHOT"
    FIX_CONTROLLED_OFFLINE_BROKER_SNAPSHOT = "FIX_CONTROLLED_OFFLINE_BROKER_SNAPSHOT"
    FIX_CONTROLLED_OFFLINE_STRATEGY_SIGNAL = "FIX_CONTROLLED_OFFLINE_STRATEGY_SIGNAL"
    FIX_CONTROLLED_OFFLINE_RISK_GUARD = "FIX_CONTROLLED_OFFLINE_RISK_GUARD"
    FIX_CONTROLLED_OFFLINE_READ_ONLY_DECISION = "FIX_CONTROLLED_OFFLINE_READ_ONLY_DECISION"
    FIX_CONTROLLED_OFFLINE_JOURNAL = "FIX_CONTROLLED_OFFLINE_JOURNAL"
    FIX_CONTROLLED_OFFLINE_METRICS = "FIX_CONTROLLED_OFFLINE_METRICS"
    FIX_CONTROLLED_OFFLINE_REPORT = "FIX_CONTROLLED_OFFLINE_REPORT"
    RESTORE_OFFLINE_REAL_BROKER_BOUNDARY = "RESTORE_OFFLINE_REAL_BROKER_BOUNDARY"
    RESTORE_OFFLINE_SECRET_BOUNDARY = "RESTORE_OFFLINE_SECRET_BOUNDARY"
    RESTORE_OFFLINE_NETWORK_BOUNDARY = "RESTORE_OFFLINE_NETWORK_BOUNDARY"
    KEEP_READ_ONLY_NO_ORDER_DECISION = "KEEP_READ_ONLY_NO_ORDER_DECISION"
    RESTORE_OFFLINE_ACCOUNT_BOUNDARY = "RESTORE_OFFLINE_ACCOUNT_BOUNDARY"
    RESTORE_OFFLINE_DATA_BOUNDARY = "RESTORE_OFFLINE_DATA_BOUNDARY"
    DELAY_SYNTHETIC_MARKET_SCENARIO_V1 = "DELAY_SYNTHETIC_MARKET_SCENARIO_V1"
    RUN_CONTROLLED_OFFLINE_RUNNER_MINIMAL_REVIEW_TEST_SUITE = "RUN_CONTROLLED_OFFLINE_RUNNER_MINIMAL_REVIEW_TEST_SUITE"
    APPROVE_SYNTHETIC_MARKET_SCENARIO_V1 = "APPROVE_SYNTHETIC_MARKET_SCENARIO_V1"


@dataclass(frozen=True)
class ControlledOfflineRunnerMinimalReviewFinding:
    name: str
    passed: bool
    score: int
    risks: tuple[ControlledOfflineRunnerMinimalReviewRisk, ...] = ()
    details: tuple[str, ...] = ()


@dataclass(frozen=True)
class ControlledOfflineRunnerMinimalReviewScore:
    overall_score: int
    minimal_result_score: int
    determinism_score: int
    market_scenario_score: int
    account_snapshot_score: int
    broker_snapshot_score: int
    strategy_signal_score: int
    risk_guard_score: int
    read_only_decision_score: int
    journal_score: int
    metrics_score: int
    markdown_report_score: int
    json_report_score: int
    boundary_score: int


@dataclass(frozen=True)
class ControlledOfflineRunnerMinimalReviewInput:
    minimal_result: Any = None
    minimal_input: Any = None
    controlled_offline_runner_minimal_approved: bool | None = None
    synthetic_market_scenario_v1_requested: bool = False


@dataclass(frozen=True)
class ControlledOfflineRunnerMinimalReviewResult:
    state: ControlledOfflineRunnerMinimalReviewState
    decision: ControlledOfflineRunnerMinimalReviewDecision
    score: ControlledOfflineRunnerMinimalReviewScore
    risks: tuple[ControlledOfflineRunnerMinimalReviewRisk, ...]
    recommendations: tuple[ControlledOfflineRunnerMinimalReviewRecommendation, ...]
    findings: tuple[ControlledOfflineRunnerMinimalReviewFinding, ...]
    markdown_report: str = ""
    next_phase: str = "SYNTHETIC_MARKET_SCENARIO_V1"
    offline_only: bool = True
    review_only: bool = True
    details: dict[str, Any] = field(default_factory=dict)
