
from pydantic import BaseModel
from typing import Literal

class SignalEvent(BaseModel):
    """
    Event generated by the Strategy Agent to signal a potential trade.
    """
    ticker: str
    action: Literal["buy", "sell"]
    # The confidence score of the signal, from 0 to 1
    confidence: float
    # The suggested quantity to trade.
    # The Execution Agent can adjust this based on its own logic.
    quantity: float
    order_type: Literal["market", "limit", "stop", "trailing_stop"] = "market"
    price: float | None = None

class OrderEvent(BaseModel):
    """
    Event generated by the Execution Agent after placing an order.
    """
    order_id: str
    ticker: str
    action: Literal["buy", "sell"]
    quantity: float
    status: Literal["new", "filled", "partially_filled", "canceled", "rejected"]
    timestamp: str

class RiskEvent(BaseModel):
    """
    Event generated by the Risk Agent.
    """
    event_type: Literal["high_risk_trade", "max_drawdown_exceeded"]
    details: dict

class SecurityEvent(BaseModel):
    """
    A generic event for the Security Agent.
    """
    event_type: str
    details: dict
